export const MOCK_SONGS = [
  {
    id: "song-0",
    title: "Blinding Lights",
    artist: "The Weeknd",
    level: [1],
    score: [18450],
    playCount: "42K",
    coverUrl: "https://picsum.photos/seed/song0/400/400",
    starLevel: [0],
    isSotd: true,
    isDeluxe: false,
    isLocked: [false],
    coinCost: 250,
    noteCount: [48]
  },
  {
    id: "song-1",
    title: "Levitating",
    artist: "Dua Lipa",
    level: [2, 4],
    score: [0, 0],
    playCount: "12K",
    coverUrl: "https://picsum.photos/seed/song1/400/400",
    starLevel: [0, 0],
    isSotd: false,
    isDeluxe: false,
    isLocked: [false, true],
    coinCost: 350,
    noteCount: [68, 114]
  },
  {
    id: "song-2",
    title: "Stay",
    artist: "The Kid LAROI",
    level: [3, 5, 6],
    score: [0, 0, 0],
    playCount: "25K",
    coverUrl: "https://picsum.photos/seed/song2/400/400",
    starLevel: [0, 0, 0],
    isSotd: false,
    isDeluxe: false,
    isLocked: [true, true, true],
    coinCost: 500,
    noteCount: [85, 145, 192]
  },
  {
    id: "song-3",
    title: "Shape of You",
    artist: "Ed Sheeran",
    level: [1, 2],
    score: [0, 0],
    playCount: "8K",
    coverUrl: "https://picsum.photos/seed/song3/400/400",
    starLevel: [0, 0],
    isSotd: false,
    isDeluxe: false,
    isLocked: [true, true],
    coinCost: 250,
    noteCount: [42, 75]
  },
  {
    id: "song-4",
    title: "Bad Guy",
    artist: "Billie Eilish",
    level: [4, 6],
    score: [0, 0],
    playCount: "19K",
    coverUrl: "https://picsum.photos/seed/song4/400/400",
    starLevel: [0, 0],
    isSotd: false,
    isDeluxe: true,
    isLocked: [true, true],
    coinCost: 1500,
    noteCount: [120, 210]
  },
  {
    id: "song-5",
    title: "Save Your Tears",
    artist: "The Weeknd",
    level: [2, 4],
    score: [0, 0],
    playCount: "5K",
    coverUrl: "https://picsum.photos/seed/song5/400/400",
    starLevel: [0, 0],
    isSotd: false,
    isDeluxe: false,
    isLocked: [true, true],
    coinCost: 350,
    noteCount: [72, 125]
  },
  {
    id: "song-6",
    title: "Peaches",
    artist: "Justin Bieber",
    level: [3],
    score: [0],
    playCount: "30K",
    coverUrl: "https://picsum.photos/seed/song6/400/400",
    starLevel: [0],
    isSotd: false,
    isDeluxe: false,
    isLocked: [true],
    coinCost: 500,
    noteCount: [95]
  },
  {
    id: "song-7",
    title: "Montero",
    artist: "Lil Nas X",
    level: [5, 6],
    score: [0, 0],
    playCount: "11K",
    coverUrl: "https://picsum.photos/seed/song7/400/400",
    starLevel: [0, 0],
    isSotd: false,
    isDeluxe: false,
    isLocked: [true, true],
    coinCost: 1000,
    noteCount: [155, 215]
  },
  {
    id: "song-8",
    title: "Dynamite",
    artist: "BTS",
    level: [2, 3, 4],
    score: [0, 0, 0],
    playCount: "55K",
    coverUrl: "https://picsum.photos/seed/song8/400/400",
    starLevel: [0, 0, 0],
    isSotd: false,
    isDeluxe: true,
    isLocked: [true, true, true],
    coinCost: 700,
    noteCount: [80, 110, 140]
  },
  {
    id: "song-9",
    title: "Good 4 U",
    artist: "Olivia Rodrigo",
    level: [4],
    score: [0],
    playCount: "21K",
    coverUrl: "https://picsum.photos/seed/song9/400/400",
    starLevel: [0],
    isSotd: false,
    isDeluxe: false,
    isLocked: [true],
    coinCost: 750,
    noteCount: [118]
  },
  {
    id: "song-10",
    title: "Industry Baby",
    artist: "Lil Nas X",
    level: [3, 5],
    score: [0, 0],
    playCount: "14K",
    coverUrl: "https://picsum.photos/seed/song10/400/400",
    starLevel: [0, 0],
    isSotd: false,
    isDeluxe: false,
    isLocked: [true, true],
    coinCost: 500,
    noteCount: [88, 162]
  },
  {
    id: "song-11",
    title: "As It Was",
    artist: "Harry Styles",
    level: [1, 5],
    score: [0, 0],
    playCount: "38K",
    coverUrl: "https://picsum.photos/seed/song11/400/400",
    starLevel: [0, 0],
    isSotd: false,
    isDeluxe: true,
    isLocked: [true, true],
    coinCost: 500,
    noteCount: [52, 150]
  },
  {
    id: "song-12",
    title: "About Damn Time",
    artist: "Lizzo",
    level: [2, 6],
    score: [0, 0],
    playCount: "9K",
    coverUrl: "https://picsum.photos/seed/song12/400/400",
    starLevel: [0, 0],
    isSotd: false,
    isDeluxe: false,
    isLocked: [true, true],
    coinCost: 350,
    noteCount: [78, 198]
  },
  {
    id: "song-13",
    title: "First Class",
    artist: "Jack Harlow",
    level: [3],
    score: [0],
    playCount: "17K",
    coverUrl: "https://picsum.photos/seed/song13/400/400",
    starLevel: [0],
    isSotd: false,
    isDeluxe: false,
    isLocked: [true],
    coinCost: 500,
    noteCount: [82]
  },
  {
    id: "song-14",
    title: "Heat Waves",
    artist: "Glass Animals",
    level: [2, 3, 5],
    score: [0, 0, 0],
    playCount: "60K",
    coverUrl: "https://picsum.photos/seed/song14/400/400",
    starLevel: [0, 0, 0],
    isSotd: false,
    isDeluxe: false,
    isLocked: [true, true, true],
    coinCost: 1000,
    noteCount: [74, 98, 158]
  },
  {
    id: "song-15",
    title: "Enemy",
    artist: "Imagine Dragons",
    level: [4],
    score: [0],
    playCount: "28K",
    coverUrl: "https://picsum.photos/seed/song15/400/400",
    starLevel: [0],
    isSotd: false,
    isDeluxe: true,
    isLocked: [true],
    coinCost: 1500,
    noteCount: [122]
  },
  {
    id: "song-16",
    title: "Shivers",
    artist: "Ed Sheeran",
    level: [3],
    score: [0],
    playCount: "13K",
    coverUrl: "https://picsum.photos/seed/song16/400/400",
    starLevel: [0],
    isSotd: false,
    isDeluxe: false,
    isLocked: [true],
    coinCost: 500,
    noteCount: [92]
  },
  {
    id: "song-17",
    title: "Glimpse of Us",
    artist: "Joji",
    level: [1, 6],
    score: [0, 0],
    playCount: "44K",
    coverUrl: "https://picsum.photos/seed/song17/400/400",
    starLevel: [0, 0],
    isSotd: false,
    isDeluxe: false,
    isLocked: [true, true],
    coinCost: 250,
    noteCount: [45, 185]
  },
  {
    id: "song-18",
    title: "Running Up That Hill",
    artist: "Kate Bush",
    level: [5],
    score: [0],
    playCount: "33K",
    coverUrl: "https://picsum.photos/seed/song18/400/400",
    starLevel: [0],
    isSotd: false,
    isDeluxe: true,
    isLocked: [true],
    coinCost: 2000,
    noteCount: [142]
  },
  {
    id: "song-19",
    title: "Left and Right",
    artist: "Charlie Puth",
    level: [2, 5],
    score: [0, 0],
    playCount: "22K",
    coverUrl: "https://picsum.photos/seed/song19/400/400",
    starLevel: [0, 0],
    isSotd: false,
    isDeluxe: false,
    isLocked: [true, true],
    coinCost: 350,
    noteCount: [65, 148]
  },
  {
    id: "song-20",
    title: "Hold Me Closer",
    artist: "Elton John",
    level: [2, 4],
    score: [0, 0],
    playCount: "6K",
    coverUrl: "https://picsum.photos/seed/song20/400/400",
    starLevel: [0, 0],
    isSotd: false,
    isDeluxe: false,
    isLocked: [true, true],
    coinCost: 350,
    noteCount: [70, 128]
  },
  {
    id: "song-21",
    title: "Unholy",
    artist: "Sam Smith",
    level: [4],
    score: [0],
    playCount: "31K",
    coverUrl: "https://picsum.photos/seed/song21/400/400",
    starLevel: [0],
    isSotd: false,
    isDeluxe: false,
    isLocked: [true],
    coinCost: 750,
    noteCount: [112]
  },
  {
    id: "song-22",
    title: "Cuff It",
    artist: "Beyoncé",
    level: [3],
    score: [0],
    playCount: "19K",
    coverUrl: "https://picsum.photos/seed/song22/400/400",
    starLevel: [0],
    isSotd: false,
    isDeluxe: true,
    isLocked: [true],
    coinCost: 1000,
    noteCount: [86]
  },
  {
    id: "song-23",
    title: "Anti-Hero",
    artist: "Taylor Swift",
    level: [1, 3, 5],
    score: [0, 0, 0],
    playCount: "82K",
    coverUrl: "https://picsum.photos/seed/song23/400/400",
    starLevel: [0, 0, 0],
    isSotd: false,
    isDeluxe: false,
    isLocked: [true, true, true],
    coinCost: 250,
    noteCount: [46, 94, 154]
  },
  {
    id: "song-24",
    title: "Made You Look",
    artist: "Meghan Trainor",
    level: [2],
    score: [0],
    playCount: "15K",
    coverUrl: "https://picsum.photos/seed/song24/400/400",
    starLevel: [0],
    isSotd: false,
    isDeluxe: false,
    isLocked: [true],
    coinCost: 350,
    noteCount: [62]
  },
  {
    id: "song-25",
    title: "Flowers",
    artist: "Miley Cyrus",
    level: [1],
    score: [0],
    playCount: "95K",
    coverUrl: "https://picsum.photos/seed/song25/400/400",
    starLevel: [0],
    isSotd: false,
    isDeluxe: false,
    isLocked: [true],
    coinCost: 250,
    noteCount: [55]
  },
  {
    id: "song-26",
    title: "Kill Bill",
    artist: "SZA",
    level: [6],
    score: [0],
    playCount: "41K",
    coverUrl: "https://picsum.photos/seed/song26/400/400",
    starLevel: [0],
    isSotd: false,
    isDeluxe: true,
    isLocked: [true],
    coinCost: 3000,
    noteCount: [205]
  },
  {
    id: "song-27",
    title: "Boy's a Liar Pt. 2",
    artist: "PinkPantheress",
    level: [2, 3, 5],
    score: [0, 0, 0],
    playCount: "27K",
    coverUrl: "https://picsum.photos/seed/song27/400/400",
    starLevel: [0, 0, 0],
    isSotd: false,
    isDeluxe: false,
    isLocked: [true, true, true],
    coinCost: 350,
    noteCount: [66, 102, 166]
  },
  {
    id: "song-28",
    title: "Cruel Summer",
    artist: "Taylor Swift",
    level: [3],
    score: [0],
    playCount: "73K",
    coverUrl: "https://picsum.photos/seed/song28/400/400",
    starLevel: [0],
    isSotd: false,
    isDeluxe: true,
    isLocked: [true],
    coinCost: 1000,
    noteCount: [105]
  },
  {
    id: "song-29",
    title: "Paint The Town Red",
    artist: "Doja Cat",
    level: [4, 6],
    score: [0, 0],
    playCount: "36K",
    coverUrl: "https://picsum.photos/seed/song29/400/400",
    starLevel: [0, 0],
    isSotd: false,
    isDeluxe: false,
    isLocked: [true, true],
    coinCost: 750,
    noteCount: [132, 225]
  }
];
